login: "my_42_login"
password: "my_42_password"
refresh: 30
range: 7
disponibility: "07:00-20:00"
send:
  telegram:
    token: '000000000:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    chat_id: '0000000000'
projects:
  - "debug_my_slots"
avoid_spam: true
